### ISSUE TITLE
The process 'usr/bin/git' failed with exit code 1

### ISSUE THREAD

**Issue by ciesielskico** [ArtiomTr/jest-coverage-report-action#192]
### Describe a bug

Action fails with error `The process 'usr/bin/git' failed with exit code 1`

### Details

-   Action version: 2-rc.6
-   OS, where your action is running (windows, linux): Linux, Node v14.x

```
- name: Run unit tests
  uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.6
  with:
    github-token: ${{ secrets.GITHUB_TOKEN }}
    skip-step: install
    test-script: npm run test:ci -- --coverageReporters="text" --coverageReporters="text-summary"
    # threshold: 50
```

```
=============================== Coverage summary ===============================
Statements   : 48.58% ( 1647/3390 )
Branches     : 10.36% ( 109/1052 )
Functions    : 16.04% ( 136/848 )
Lines        : 46.16% ( 1412/3059 )
================================================================================

Test Suites: 14 skipped, 33 passed, 33 of 47 total
Tests:       15 skipped, 1 todo, 68 passed, 84 total
Snapshots:   0 total
Time:        57.721 s
Test results written to: report.json
Running tests ended
Begin collecting coverage...
Collecting coverage ended
Begin parsing coverage...
Parsing coverage ended
Head coverage collection ended
Begin switching to base branch...
/usr/bin/git fetch --all --depth=1
Fetching origin
fatal: could not read Username for 'https://github.com': No such device or address
error: Could not fetch origin
Error fetching git repository Error: The process '/usr/bin/git' failed with exit code 1
    at Xn._setResult (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.0-rc.6/dist/index.js:9:17173)
    at Xn.CheckComplete (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.0-rc.6/dist/index.js:9:16763)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.0-rc.6/dist/index.js:9:15756)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
/usr/bin/git checkout -f main
error: pathspec 'main' did not match any file(s) known to git
Switching to base branch failed
Error: Error: The process '/usr/bin/git' failed with exit code 1
Switching to base branch ended
Begin base coverage collection...
Base coverage collection skipped
Base coverage collection ended
Begin generating report...
Generating report ended
Begin report publish...
Report publish ended
Begin failed tests' annotations publication...
Failed tests' annotations publication skipped
Failed tests' annotations publication ended
Begin coverage annotations publication...
Coverage annotations publication ended
Error: Jest coverage report action failed
Error: Process completed with exit code 1.
```

**Comment by ArtiomTr** [comment]
Hello @ciesielskico,

Are you trying to run this action in private repository?

**Comment by ciesielskico** [comment]
Yes, and I am using checkout@v2 with persist-credentials: false, which I need for a specific package when installing dependencies. Enabling that fixes the above issue( but breaks npm install). 

So it's not a bug related to your package but something to do with the checkout action.

**Comment by ciesielskico** [comment]
I wrote my own shell script to extract coverage and paste it as a PR comment, which I can't unfortunately share :) But it's a nice weekend project.
