### ISSUE TITLE
Error: Unable to locate executable file: pnpm

### ISSUE THREAD

**Issue by djdembeck** [ArtiomTr/jest-coverage-report-action#290]
> Begin installing dependencies...
Installing dependencies failed
Error: Error: Unable to locate executable file: pnpm. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
Error: Unable to locate executable file: pnpm. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
    at Object.<anonymous> (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2/dist/index.js:10:9277)
    at Generator.next (<anonymous>)
    at n (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2/dist/index.js:10:7162)
Installing dependencies ended

Action yaml:
https://github.com/laxamentumtech/audnexus/blob/develop/.github/workflows/jest-coverage.yml

Action result:
https://github.com/laxamentumtech/audnexus/runs/7045498277?check_suite_focus=true

**Comment by djdembeck** [comment]
Resolved. Had to add pnpm `uses` in the yaml:

```
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
```

https://github.com/laxamentumtech/audnexus/commit/76d02a45177297e99824a6c90d6ed0e30b5ccb38
