### ISSUE TITLE
Update to v3 failed with Error: iconType must be one of the following values: emoji, ascii, unicode

### ISSUE THREAD

**Issue by iamfj** [ArtiomTr/jest-coverage-report-action#386]
### Describe a bug

After updating from v2 to v3 I get the following error message when running the jest build step. Since I have no special configuration, I assume that a bug in the action is responsible for this.

```log
Running using node v18.16.1
Begin initialization stage...
Initialization stage failed
Error: Error: iconType must be one of the following values: emoji, ascii, unicode
iconType must be one of the following values: emoji, ascii, unicode
Error: iconType must be one of the following values: emoji, ascii, unicode
iconType must be one of the following values: emoji, ascii, unicode
    at sC (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v3/dist/index.js:2220:3460)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ei (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v3/dist/index.js:2221:158)
    at async UD (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v3/dist/index.js:22[30](https://github.com/***/***/actions/runs/5636375272/job/15268391600?pr=91#step:4:32):14458)
Initialization stage ended
/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v3/dist/index.js:2230
```

### Expected behavior

I would expect the test to run through with the below configuration without error.

### Details

-   Action version: v3
-   OS, where your action is running (windows, linux): ubuntu-latest
-   <details><summary>workflow.yml file</summary>

        
        jobs:
         jest:
           runs-on: ubuntu-latest
           permissions:
             checks: write
             pull-requests: write
             contents: write
           steps:
             - name: Checkout
               uses: actions/checkout@v3
             - name: Install node.js
               uses: actions/setup-node@v3
               with:
                 node-version-file: .nvmrc
             - name: Jest with Coverage
               uses: ArtiomTr/jest-coverage-report-action@v3
        

    </details>

-   <details><summary>Screenshots</summary>

     ![image](https://github.com/ArtiomTr/jest-coverage-report-action/assets/24557998/6baec3a0-089e-4cd1-bf82-4144a275961c)

    </details>

### Additional context

If necessary, I can also attach the complete log of this runs.

**Comment by ArtiomTr** [comment]
Hello @iamfj :wave:,

The `v3` version is not released yet, actually, I've just started working on it 😄

I need a few months to finish it, so yeah, currently it is not even "alpha" or "beta" - it just doesn't work at all.

**Comment by schorfES** [comment]
Dependabot has suggested the update from `v2` to `v3` in my repositories. I am not sure where it got the version from. If it is the GIT tag, maybe it makes sense not to tag the version until you have a stable version.

**Comment by ArtiomTr** [comment]
Thank you, didn't know that dependabot suggests updating actions, even if there is no release tag. I'll rename the branch

**Comment by ArtiomTr** [comment]
Renamed `v3` branch to `wip-v3`, so dependabot should not suggest updating anymore 👍

**Comment by iamfj** [comment]
Right, dependabot suggested it for me too. Thanks for the fast response!
