### ISSUE TITLE
Action fails when running on Node v14.16.1

### ISSUE THREAD

**Issue by sagodi97** [ArtiomTr/jest-coverage-report-action#423]
### Describe a bug

Hi there! Can't pinpoint exactly what is the issue, but ever since v2.2.7  (#412) the action fails when running on Node v14.16.1 with:

```
Run ArtiomTr/jest-coverage-report-action@v2.2.7
Run $GITHUB_ACTION_PATH/run.sh
Running using node v14.16.1
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'node:module'
Require stack:
- /home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.2.7/dist/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.2.7/dist/index.js:2137:2104)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:9[28](https://github.com/SpotOnInc/campaign-web/actions/runs/8186968767/job/22386466710#step:7:30):[32](https://github.com/SpotOnInc/campaign-web/actions/runs/8186968767/job/22386466710#step:7:34))
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.2.7/dist/index.js'
  ]
}
Error: Process completed with exit code 1.
```

### Expected behavior

Expected the action to run as usual.

### Details

-   Action version: 2.2.7
-   OS, where your action is running (windows, linux): linux

-   <details><summary>Screenshots</summary>
        <img width="1405" alt="image" src="https://github.com/ArtiomTr/jest-coverage-report-action/assets/36556883/2e4f39c1-7b74-4e6a-a80f-b93926dde142">

    </details>

**Comment by mathiasfk** [comment]
Same thing happens to me, I'm using node v12.22.12. The last successful execution was using jest-coverage-report-action@v2.2.6
